filegroup(
    name = "config_json",
    srcs = [
        "bb-browser.json",
        "bb-event-service.json",
        "bb-runner.json",
        "bb-scheduler.json",
        "bb-storage.json",
        "bb-worker.json"
    ],
    visibility = ["//visibility:public"]
)
